"""make user_id nullable

Revision ID: 179910be806d
Revises: c5840d435d86
Create Date: 2025-11-26 11:02:52.859796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179910be806d'
down_revision = 'c5840d435d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
