"""Add image_path and detected_image_path to detections

Revision ID: 48b8111ecf88
Revises: d66f6aaa2cce
Create Date: 2025-11-26 14:56:57.642334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b8111ecf88'
down_revision = 'd66f6aaa2cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('detected_image_path', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_column('detected_image_path')
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
